exports.SPACE_OWNER_GREETING = 'SPACE_OWNER_GREETING';
exports.CLIENT_JOIN_ROOM = 'CLIENT_JOIN_ROOM';
exports.REQUEST_CLIENT_APPOINTMENT = 'REQUEST_CLIENT_APPOINTMENT';
exports.CLIENT_SUBMIT_APPOINTMENT = 'CLIENT_SUBMIT_APPOINTMENT';
exports.SPACE_OWNER_STATUS_CHANGE = 'SPACE_OWNER_STATUS_CHANGE';
exports.CLIENT_LEAVE = 'CLIENT_LEAVE';
